# Generated by Django 5.1 on 2024-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app_pr1", "0002_harmful_ingredients_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_type",
            name="product_image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
